version: '3.9'
services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: America/Colombia/Bogota
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpass"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017

  emqx:
    container_name: emqx
    image: emqx/emqx:5.0.4
    restart: always
    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8085:8081
    links:
      - mongo
    extra_hosts:
      - "localhost:192.168.0.109" ##para pruebas en estado de desarrollo
    volumes:
      - ./emqxconf:/opt/emqx/data/configs/  ##New Mongo Connection
    
    environment:
      
      EMQX_NAME: IoT_DEV
      EMQX_HOST: 127.0.0.1
      TZ: America/Colombia/Bogota

      #DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "dashpass"

      EMQX_LISTENERS__TCP__DEFAULT__MAX_CONNECTIONS: 1000

      EMQX_AUTHORIZATION__NO_MATCH: deny
      EMQX_AUTHORIZATION__SOURCES__1__ENABLE: 'false'