version: '3.7'

volumes:
  vol-emqx-data:
    name: foo-emqx-data

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017

  emqx:
    container_name: emqx
    image: emqx/emqx:5.0.4
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8085:8081
    links:
      - mongo
    extra_hosts:
      - "localhost:192.168.0.107" ##para pruebas en estado de desarrollo
    volumes:
      - vol-emqx-data:/opt/emqx/data/  #Persistencia
    environment:
      EMQX_NAME: IoT_DEV
      EMQX_HOST: 127.0.0.1
      TZ: "${TZ}"

      #DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_PASSWORD: '"${EMQX_DASHBOARD__DEFAULT_PASSWORD}"'
      EMQX_LISTENERS__TCP__DEFAULT__MAX_CONNECTIONS: 1000

      EMQX_AUTHORIZATION__NO_MATCH: '"deny"'
      EQMX_AUTHORIZATION__DENY_ACTION: '"ignore"'
      EMQX_AUTHORIZATION__SOURCES__1__ENABLE: '"false"'
      EMQX_AUTHORIZATION__SOURCES__2__ENABLE: '"true"'
      EMQX_AUTHORIZATION__SOURCES__2__COLLECTION: '"${EMQX_AUTH_COLLECTION}"'
      EMQX_AUTHORIZATION__SOURCES__2__DATABASE: '"${EMQX_AUTH_DATABASE}"'
      EMQX_AUTHORIZATION__SOURCES__2__FILTER: '"${EMQX_AUTH_FILTER}"' ##hay que ajustar esta linea
      EMQX_AUTHORIZATION__SOURCES__2__SERVER: '"${EMQX_AUTH_SERVER}"'
      EMQX_AUTHORIZATION__SOURCES__2__MONGO_TYPE: '"${EMQX_AUTH_MONGO_TYPE}"'
      EMQX_AUTHORIZATION__SOURCES__2__PASSWORD: '"${EMQX_AUTH_PASSWORD}"'
      EMQX_AUTHORIZATION__SOURCES__2__POOL_SIZE: '"${EMQX_AUTH_POOL_SIZE}"'
      EMQX_AUTHORIZATION__SOURCES__2__USERNAME: '"${EMQX_AUTH_USERNAME}"'
      EMQX_AUTHORIZATION__SOURCES__2__TYPE: '"${EMQX_AUTH_TYPE}"'


      #EMQX_AUTHENTICATION__1__ENABLE: '"false"'
      EMQX_AUTHENTICATION__1__BACKEND: '"${EMQX_AUTH_TYPE}"'
      EMQX_AUTHENTICATION__1__COLLECTION: '"${EMQX_AUTHN_COLLECTION}"'
      EMQX_AUTHENTICATION__1__DATABASE: '"${EMQX_AUTH_DATABASE}"'
      EMQX_AUTHENTICATION__1__ENABLE: '"true"'
      EMQX_AUTHENTICATION__1__FILTER: '"${EMQX_AUTH_FILTER}"' ##hay que ajustar esta linea
      EMQX_AUTHENTICATION__1__IS_SUPERUSER_FIELD: '"${EMQX_AUTHN_FIELD}"'
      EMQX_AUTHENTICATION__1__MECHANISM: '"password_based"'
      EMQX_AUTHENTICATION__1__MONGO_TYPE: '"${EMQX_AUTH_MONGO_TYPE}"'
      EMQX_AUTHENTICATION__1__PASSWORD: '"${EMQX_AUTH_PASSWORD}"'
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__NAME: '"plain"' 
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__SALT_POSITION: '"disable"'
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_FIELD: '"${EMQX_AUTHN_HASH_FIELD}"'
      EMQX_AUTHENTICATION__1__POOL_SIZE: '"${EMQX_AUTH_POOL_SIZE}"'
      EMQX_AUTHENTICATION__1__SALT_FIELD: '"salt"'
      EMQX_AUTHENTICATION__1__SERVER: '"${EMQX_AUTH_SERVER}"'
      EMQX_AUTHENTICATION__1__SRV_RECORD: '"false"'
      EMQX_AUTHENTICATION__1__USERNAME: '"${EMQX_AUTH_USERNAME}"'