version: '3.7'

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017

  emqx:
    container_name: emqx
    image: emqx/emqx:5.0.4
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8085:8081
    links:
      - mongo
    extra_hosts:
      - "localhost:192.168.0.107" ##para pruebas en estado de desarrollo
    volumes:
      - ./emqxconf:/opt/emqx/data/configs/  ##New Mongo Connection
    environment:
      EMQX_NAME: IoT_DEV
      EMQX_HOST: "${EMQX_HOST}"
      TZ: "${TZ}"

      #DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "${EMQX_DASHBOARD__DEFAULT_PASSWORD}"

      EMQX_LISTENERS__TCP__DEFAULT__MAX_CONNECTIONS: 1000

      EMQX_AUTHORIZATION__NO_MATCH: deny
      EQMX_AUTHORIZATION__DENY_ACTION: ignore
      EMQX_AUTHORIZATION__SOURCES__1__ENABLE: 'false'