version: "3.7"

services:
  node_install:
    container_name: node_install
    image: "node:16"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app

    command: sh -c "npm install"
