version: "3.7"

services:
  node_build:
    container_name: node_build
    image: "node:16"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app

    command: sh -c "npm run build"
